### PR TITLE
Merge changes from Colouring Core

### PR DESCRIPTION
**Pull request by mdsimpson42**
The latest changes from Colouring Core, to be merged into Colouring Britain.

### CODE REVIEW

**Comment by mdsimpson42** [comment]
@matkoniecz Can I have a sanity check on this? I'm trying to merge the latest changes from Colouring Core (master) to Colouring Britain (master), but there were some conflicts.

In particular, can you double-check "map.tsx" and "map-button.css", as those were the conflicting files?

I think I've set it all up correctly, but I just wanted to make sure (especially after I messed it up last time!)

**Comment by matkoniecz** [comment]
@mdsimpson42 Conflict itself sadly was to be expected (I had another idea how to apply it, but it would cause even worse conflict).

From what I see in map.tsx in switcher list

```
                            <AerialPhotosMapSwitcher/>
                            <HistoricalFootprintsSwitcher/>
                            <OpenStreetMapSwitcher/>
```

have become lost after this merge is done (between HistoricDataSwitcher and VistaSwitcher). This does not seem intentional.

**Comment by matkoniecz** [comment]
[map-button.css](https://github.com/colouring-cities/colouring-britain/pull/322/files#diff-00530c74092bedcf42a26b82a397e77a8e75087d24a5f0a247b3ad16249f09a4) looks like I would expected. 

In https://github.com/colouring-cities/colouring-britain/blob/bcfdc473d89d7e29ab44d6568565de27dc77aa84/app/src/frontend/map/openstreetmap-switcher.tsx `openstreetmap-switcher` manually applied style has become not necessary but it can be followup PR.

**Comment by matkoniecz** [comment]
Note: I have only looked at code, not run it.

**Comment by mdsimpson42** [comment]
Okay, I've made some updates that seem to have fixed the behaviour of the Switchers. I've tested the code and it all seems to be working. Will merge and deploy to Staging.

**Pull request merged**
