### PR TITLE
Feature/merge upstream

### PR DESCRIPTION
**Pull request by matkoniecz**

### CODE REVIEW

**Comment by matkoniecz** [comment]
blocked by https://github.com/colouring-cities/colouring-core/issues/1399

**Comment by mdsimpson42** [comment]
If the only problem was the documentation link, that has now been fixed on the master branch on Colouring Core.

**Comment by mdsimpson42** [comment]
Should we merge this first, then pull across the category changes?

**Comment by matkoniecz** [comment]
I would merge that together, so effectively it makes this PR outdated. I will close it.

Thanks for checking for other link breakage!

**Pull request closed without merging**
