### PR TITLE
assume style based on age data for display

### LINKED ISSUE #161: allow 'age' entry to automatically update and override 'architectural style' data in map style
Automatically update 'Architectural style' when building 'age 'is entered - (not other way round)

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #161

### CODE REVIEW

**Comment by matkoniecz** [comment]
@polly64 It is published on staging right now and looks like it is working well!

**Review by mdsimpson42 — APPROVED** [review]
I'm happy with these changes. Maybe @polly64 should test them on Staging and confirm they are working correctly before we merge them? 

Turn this from a draft when its ready to be merged.

**Comment by polly64** [comment]
will test later , won't load on staging at moment

**Comment by matkoniecz** [comment]
moved to draft as I need to apply some requests from Polly (age overriding style if both specified)

**Pull request merged**
